steps:
  # Step 1: Build Docker image
  - name: 'build'
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'Dockerfile']

  # Step 2: Push Docker image to Google Container Registry (GCR)
  - name: 'push'
    args: ['push', '$_SERVICE_IMAGE']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'task-tracker'
      - '--image=$_SERVICE_IMAGE'
      - '--region=$_SERVICE_IMAGE'
      - '--platform=managed'
      - '--allow-unauthenticated'

# Timeout for the build process
timeout: '1200s'

substitutions:
  _PROJECT_ID: 'your-project-id'  # Replace with your GCP project ID
  _REGION: 'europe-west3'          # Replace with your desired region
  _IMAGE_NAME: 'task-tracker'      # Replace with your desired image name